export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  OTP_SERVICE_UNAVAILABLE: 'OTP_SERVICE_UNAVAILABLE',
  OTP_EMPTY_PLAN: 'OTP_EMPTY_PLAN',
  OTP_GRAPHQL_ERROR: 'OTP_GRAPHQL_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  LEG_NOT_FOUND: 'LEG_NOT_FOUND',
  LEG_ALREADY_USED: 'LEG_ALREADY_USED',
  TICKET_EXPIRED: 'TICKET_EXPIRED',
  NO_TICKETABLE_LEGS: 'NO_TICKETABLE_LEGS',
  STATION_LIMIT_EXCEEDED: 'STATION_LIMIT_EXCEEDED',
};

export function makeError(code, message, details = {}) {
  return { error: { code, message, details } };
}
