// Curated Arabic lexicon for composing route place-name translations.
//
// EXACT: normalized English full/segment name -> Arabic. Keys are normalized the
// same way as normalizePlace() in src/services/placeLocalization.ts (lowercase,
// hyphens/underscores -> spaces, collapsed whitespace). Values are reviewed
// Arabic. The generator resolves a full name by:
//   1) exact full-name match here, else
//   2) splitting a route compound "A - B" / "A-B" into segments, each of which
//      must be an EXACT entry, then joining with " - ".
// Anything not fully resolved is left untranslated (English fallback at runtime).
//
// Grow coverage by adding entries here and re-running generatePlaceTranslations.mjs.

// Normalize exactly like the runtime + generator (keep in sync).
function norm(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ");
}

const RAW = {
  // ── Metro network (all 61 stations) ──────────────────────────────────────
  "Abbassiya": "العباسية",
  "Abdou Pasha": "عبده باشا",
  "Ain Helwan": "عين حلوان",
  "Ain Shams": "عين شمس",
  "Al-Ahram": "الأهرام",
  "Al-Sayeda Zeinab": "السيدة زينب",
  "Al-Shohadaa": "الشهداء",
  "Attaba": "العتبة",
  "Bab El-Shaaria": "باب الشعرية",
  "Bohooth": "البحوث",
  "Cairo University": "جامعة القاهرة",
  "Dar El-Salam": "دار السلام",
  "Dokki": "الدقي",
  "El-Demerdash": "الدمرداش",
  "El-Geish": "الجيش",
  "El-Giza": "الجيزة",
  "El-Maasara": "المعصرة",
  "El-Malek El-Saleh": "الملك الصالح",
  "El-Marg": "المرج",
  "El-Matareyya": "المطرية",
  "El-Mounib": "المنيب",
  "El-Zahraa": "الزهراء",
  "Ezbet El-Nakhl": "عزبة النخل",
  "Fair Zone": "منطقة المعارض",
  "Faisal": "فيصل",
  "Ghamra": "غمرة",
  "Hadayek El-Maadi": "حدائق المعادي",
  "Hadayek Helwan": "حدائق حلوان",
  "Hadayeq El-Zaitoun": "حدائق الزيتون",
  "Hammamat El-Qobba": "حمامات القبة",
  "Helmeyet El-Zaitoun": "حلمية الزيتون",
  "Helwan": "حلوان",
  "Helwan University": "جامعة حلوان",
  "Khalafawy": "الخلفاوي",
  "Kobri El-Qobba": "كوبري القبة",
  "Koleyet El-Banat": "كلية البنات",
  "Kolleyyet El-Zeraa": "كلية الزراعة",
  "Kozzika": "كوزيكا",
  "Maadi": "المعادي",
  "Manshiet El-Sadr": "منشية الصدر",
  "Mar Girgis": "مار جرجس",
  "Masarra": "مسرة",
  "Mezallat": "المظلات",
  "Mohamed Naguib": "محمد نجيب",
  "Nasser": "ناصر",
  "New El-Marg": "المرج الجديدة",
  "Omm El-Misryeen": "أم المصريين",
  "Opera": "الأوبرا",
  "Orabi": "عرابي",
  "Rod El Farag": "روض الفرج",
  "Saad Zaghloul": "سعد زغلول",
  "Sadat": "السادات",
  "Sakanat El-Maadi": "ثكنات المعادي",
  "Sakiat Mekki": "ساقية مكي",
  "Saray El-Qobba": "سراي القبة",
  "Shubra El-Kheima": "شبرا الخيمة",
  "St. Teresa": "سانت تريزا",
  "Stadium": "الاستاد",
  "Tora El-Asmant": "طرة الأسمنت",
  "Tora El-Balad": "طرة البلد",
  "Wadi Hof": "وادي حوف",

  // Metro station name variants seen in stop/route text
  "Abbasseya": "العباسية",
  "Ataba": "العتبة",
  "Al Demerdash Metro Station": "محطة الدمرداش",
  "Cairo University Metro Station": "محطة جامعة القاهرة",
  "Cairo Universty Metro Station": "محطة جامعة القاهرة",
  "Faisal Metro Station": "محطة فيصل",
  "Gamal Abd Al Nasser Metro Station": "محطة جمال عبد الناصر",
  "Giza Metro Station": "محطة الجيزة",
  "Koleyet Al Banat Metro Station": "محطة كلية البنات",
  "Mohamed Naguib Metro Station": "محطة محمد نجيب",
  "Rod Al Farag Metro Station": "محطة روض الفرج",
  "Saint Teresa Metro Station": "محطة سانت تريزا",
  "Al Mazallat Metro Station": "محطة المظلات",
  "Zahraa Metro Station": "محطة الزهراء",
  "Hadayek Al Qobba Station": "محطة حدائق القبة",
  "Rod El Farag": "روض الفرج",
  "Sakanat El-Maadi": "ثكنات المعادي",

  // ── Metro line long-names (appear in "towards …") ────────────────────────
  "Metro Line 1": "الخط الأول للمترو",
  "Metro Line 2": "الخط الثاني للمترو",
  "Metro Line 3": "الخط الثالث للمترو",

  // ── Cities / districts / common areas (segments of bus compounds) ────────
  "6th of October": "السادس من أكتوبر",
  "6th Of October City Authority": "جهاز مدينة السادس من أكتوبر",
  "6th Of October University": "جامعة السادس من أكتوبر",
  "Sheikh Zayed": "الشيخ زايد",
  "Nasr City": "مدينة نصر",
  "New Cairo": "القاهرة الجديدة",
  "Obour": "العبور",
  "Al Shorouq": "الشروق",
  "10th of Ramadan": "العاشر من رمضان",
  "New Marg": "المرج الجديدة",
  "Ring Road": "الطريق الدائري",
  "Haram": "الهرم",
  "Haram Street": "شارع الهرم",
  "Imbaba": "إمبابة",
  "Ramses": "رمسيس",
  "Ramses Railway Station": "محطة مصر رمسيس",
  "Heliopolis": "مصر الجديدة",
  "Shubra": "شبرا",
  "Shubra Al Kheima": "شبرا الخيمة",
  "Tahrir Square": "ميدان التحرير",
  "Downtown Cairo": "وسط البلد",
  "Zamalek": "الزمالك",
  "Giza Square": "ميدان الجيزة",
  "Lebanon Square (Medan Lebnan)": "ميدان لبنان",
  "Medan Lebnan": "ميدان لبنان",
  "Qalyub": "قليوب",
  "Bahteem": "بهتيم",
  "Mostorod Station": "محطة مسطرد",
  "Dawaran Shubra": "دوران شبرا",
  "Kit Kat Square": "ميدان الكيت كات",
  "Kit Kat District": "حي الكيت كات",
  "Roxy": "روكسي",
  "Abdeen": "عابدين",
  "Manshiyat Nasser": "منشية ناصر",
  "Basateen": "البساتين",
  "Dar Al Salam": "دار السلام",
  "Kattameya": "القطامية",
  "Kattameya Church": "كنيسة القطامية",
  "Saqr Quraish": "صقر قريش",
  "Alf Maskan": "ألف مسكن",
  "Alf Masnaa": "ألف مصنع",
  "Moneeb": "المنيب",
  "Moneeb Konayyesa": "المنيب الكنيسة",
  "Al Souq Al Qadeem": "السوق القديم",
  "Al Hossary": "الحصري",
  "Al Hossary Square": "ميدان الحصري",
  "Al Hossary Station": "محطة الحصري",
  "Laylat Al Qadr": "ليلة القدر",
  "Dolce": "دولتشي",
  "Bashayer": "البشاير",
  "Magda Square": "ميدان ماجدة",
  "Masaken Othman": "مساكن عثمان",
  "Smart Village (Al Qarya Al Zakeya)": "القرية الذكية",
  "Mashaal Smart Village (Al Qarya Al Zakeya)": "مشعل القرية الذكية",
  "Remaya Square": "ميدان الرماية",
  "Al Remaya Square": "ميدان الرماية",
  "Sphinx Airport": "مطار سفنكس",
  "Zahraa Madinet Nasr": "زهراء مدينة نصر",
  "Zahraa Nasr City": "زهراء مدينة نصر",
  "Omaal Square": "ميدان العمال",
  "Ommal Square - 5th Settlement": "ميدان العمال - التجمع الخامس",
  "Mahkama": "المحكمة",
  "Hay Asher": "الحي العاشر",
  "Police Academy": "أكاديمية الشرطة",
  "Rehab Gate 6": "بوابة الرحاب 6",
  "Rehab Gate 13": "بوابة الرحاب 13",
  "Rehab Square": "ميدان الرحاب",
  "Higher Technological Institute": "المعهد التكنولوجي العالي",
  "Industrial Zone 2": "المنطقة الصناعية 2",
  "Industrial Zone 3": "المنطقة الصناعية 3",
  "Industrial Zone 4": "المنطقة الصناعية 4",

  // ── Settlements (Tagamoat) ───────────────────────────────────────────────
  "1st Settlement (Tagamoa Awwal)": "التجمع الأول",
  "First Settlement": "التجمع الأول",
  "1st Settlement": "التجمع الأول",
  "3rd Settlement (Tagamoa Thaleth)": "التجمع الثالث",
  "Third Settlement": "التجمع الثالث",
  "3rd Settlement": "التجمع الثالث",
  "5th Settlement": "التجمع الخامس",
  "5th Settlement City Authority": "جهاز التجمع الخامس",

  // ── Frequent proper-name stops / fragments (incl. screenshot) ────────────
  "Abd Al Moneim Riad": "عبد المنعم رياض",
  "Abou Al Reesh": "أبو الريش",
  "Mostafa Al Nahas": "مصطفى النحاس",
  "Abbas Al Akkad": "عباس العقاد",
  "Awwal Abbas Al Akkad": "أول عباس العقاد",
  "Awwal Makram Ebeid": "أول مكرم عبيد",
  "Makram Ebeid": "مكرم عبيد",
  "Al Tayaran": "الطيران",
  "Al Tawheed Wal Nour - Mostafa Al Nahas": "التوحيد والنور - مصطفى النحاس",
  "Al Tayaran - Mostafa Al Nahas": "الطيران - مصطفى النحاس",
  "Khedr Al Touny - Al Tayaran": "خضر التوني - الطيران",
  "Zaker Hussein - Al Tayaran": "ذاكر حسين - الطيران",
  "Greek Hospital": "المستشفى اليوناني",
  "Kids Land - Mostafa Al Nahas": "كيدز لاند - مصطفى النحاس",
  "Pizza Hut - Mostafa Al Nahas": "بيتزا هت - مصطفى النحاس",
  "Saint Fatima Square": "ميدان سانت فاتيما",
  "Salah Salem": "صلاح سالم",
  "Gesr Al Suez": "جسر السويس",
  "Al Manial": "المنيل",
  "Al Geish Square": "ميدان الجيش",
  "Al Horreya Square": "ميدان الحرية",
  "Sudan Street": "شارع السودان",
  "Noubar Street": "شارع نوبار",
  "Bostan Street": "شارع البستان",
  "Ahmed Helmy": "أحمد حلمي",
  "Abboud": "عبود",
  "Khalafawy Square": "ميدان الخلفاوي",
  "Al Khalafawy Square": "ميدان الخلفاوي",

  // ── Acronyms / institutions ──────────────────────────────────────────────
  "AUC": "الجامعة الأمريكية",
  "CAPMAS": "الجهاز المركزي للتعبئة والإحصاء",
  "ENPPI": "إنبي",
  "EMPC": "مدينة الإنتاج الإعلامي",
  "Egyptian Media Production City - EMPC": "مدينة الإنتاج الإعلامي",

  // ── Extra segments to fix half-translated route compounds ────────────────
  "Badr": "بدر",
  "Hyper": "هايبر",
  "Gas": "محطة الوقود",
  "Isko": "إسكو",
  "Mamaleek": "المماليك",
  "Motamayez": "المتميز",
  "Al Motamayez": "المتميز",
  "District 6": "الحي السادس",
  "District 8": "الحي الثامن",
  "District 10": "الحي العاشر",
  "District 11": "الحي الحادي عشر",
  "District 16": "الحي السادس عشر",
  "7th District": "الحي السابع",
  "7th District (Hay Al Sabea)": "الحي السابع",
  "8th District": "الحي الثامن",
  "8th District (Hay Al Thamen)": "الحي الثامن",
  "Al Souk Al Qadeem": "السوق القديم",
  "Al Mazallat": "المظلات",
  "Al Al Mazallat": "المظلات",
  "Al Moassasa": "المؤسسة",
  "Al Joman": "الجمان",
  "Qawmeya Arabeya": "القومية العربية",
  "Zayed 2000": "زايد 2000",
  "Zayed 2000 Gate 3": "زايد 2000 بوابة 3",
  "Ismailiya Desert Road": "طريق الإسماعيلية الصحراوي",
  "Al Marioteya Road": "طريق المريوطية",
  "Al Mansoreya Road": "طريق المنصورية",
  "26th of July Mehwar": "محور 26 يوليو",
  "Mehwar Desert Rd": "المحور الصحراوي",
  "Haram Marioteyya": "هرم مريوطية",
  "Haram Mashaal": "هرم مشعل",
  "Medan Lebnan": "ميدان لبنان",
  "Akhnatoun": "أخناتون",
  "Arabella": "أرابيلا",
  "Mahmoudeyya": "المحمودية",
  "El Hamd": "الحمد",
  "Attaba": "العتبة",
  "Masraweyya": "مصراوية",
  "Salam Nahda": "سلام نهضة",
  "Salam Nahda-Alf Maskan": "سلام نهضة - ألف مسكن",
  "Sheikh Zayed General Hospital": "مستشفى الشيخ زايد العام",
  "Total 6 October": "توتال 6 أكتوبر",

  // ── Final long-tail segments (fix remaining half-translated compounds) ────
  "Abbaseya": "العباسية",
  "Warraq": "الوراق",
  "Kattameyya": "القطامية",
  "Kan Kan": "كان كان",
  "Nissan": "نيسان",
  "Mobil": "موبيل",
  "Mostorad": "مسطرد",
  "Mostorod": "مسطرد",
  "Nasr City Towers": "أبراج مدينة نصر",
  "Al Zawya Al Hamra": "الزاوية الحمراء",
  "El Matbaa": "المطبعة",
  "Madinat Al Talaba": "مدينة الطلبة",
  "Masaken Ain Shams": "مساكن عين شمس",
  "Masaken Zainhom": "مساكن زينهم",
  "Masalla Gedeeda Matareya": "المصلى الجديدة - المطرية",
  "10th of Ramadan Station": "محطة العاشر من رمضان",
  "10th of Ramadan Station (Asher Men Ramadan)": "محطة العاشر من رمضان",
  "7th District Stop (Hay Al Sabea)": "موقف الحي السابع",
  "Mobil Mostafa Kamel Axis": "موبيل محور مصطفى كامل",
  "Holding Co. For Water & Wastewater (HCWW)": "الشركة القابضة لمياه الشرب والصرف الصحي",
};

export const EXACT = (() => {
  const out = {};
  for (const [en, ar] of Object.entries(RAW)) {
    const key = norm(en);
    if (key && ar) out[key] = ar;
  }
  return out;
})();

export { norm };
